server:
  port: 8088
spring:
  liquibase:
    enabled: true
    change-log: "classpath:liquibase/db.changelog-master.xml"
  application:
    name: demo-hibernate-envers
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # set type update will auto create table
      ddl-auto: update
      listener:
        envers:
          autoRegister: false
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
       integration:
          envers:
            enabled: true
       envers:
          audit_table_suffix: _AUDIT
          revision_field_name: REVISION_ID
          revision_type_field_name: REVISION_TYPE
          store_data_at_delete: true

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_envers_service?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: PoolHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
logging:
  level:
    root: info
